### ISSUE TITLE
Dark Theme 下选项不可见

### ISSUE THREAD

**Issue by zhucaidan** [BlueSkyXN/GPT-Models-Plus#1]
![image](https://github.com/BlueSkyXN/GPT-Models-Plus/assets/47970938/48395081-8227-418d-80aa-5a4ce313b632)

**Comment by CLAY-CMD** [comment]
确实，我也是这样

**Comment by BlueSkyXN** [comment]
> 确实，我也是这样

噗，我是从来不用暗黑模式，没想过这个问题，刚刚有个PR强制锁定背景颜色和文本颜色了，你可以试试

**Comment by zhucaidan** [comment]
好了👍
